<?php

namespace Liushoukun\LaravelProjectTools\Http\Resources\Json;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Liushoukun\LaravelProjectTools\Http\ResponseJsonService;

/**
 * Json 资源
 */
class JsonResource extends \Illuminate\Http\Resources\Json\JsonResource
{

    protected string|null $message = '';
    protected string|int  $code    = 0;
    protected array|null  $errors  = null;

    /**
     * @inheritDoc
     */
    public function __construct($resource, string $message = '', string|int $code = 0)
    {
        parent::__construct($resource);
        $this->message = $message;
        $this->code    = $code;
    }

    /**
     * @inheritDoc
     */
    public static function collection($resource, string $message = '', string|int $code = 0) : AnonymousResourceCollection
    {
        return (parent::collection($resource))->additional(ResponseJsonService::additional($code, $message));
    }


    public function addCustomizeAdditional() : JsonResource
    {
        return $this->additional(array_merge_recursive($this->additional, $this->getCustomizeAdditional()));
    }

    public function getCustomizeAdditional() : array
    {
        return ResponseJsonService::additional($this->code, $this->message, $this->errors);
    }

    /**
     * @param string|null $message
     * @return $this
     */
    public function setMessage(?string $message)
    {
        $this->message = $message;
        return $this;
    }


    /**
     * @param int|string $code
     * @return $this
     */
    public function setCode(int|string $code)
    {
        $this->code = $code;
        return $this;
    }

    /**
     * @inheritDoc
     */
    public function toResponse($request) : JsonResponse
    {
        $this->addCustomizeAdditional();
        return parent::toResponse($request); // TODO: Change the autogenerated stub
    }


}
